{"name": "test_delete_test_plan_api_error", "status": "passed", "description": "Test deletion of a test plan with exception.", "attachments": [{"name": "log", "source": "b363b645-7ae3-4375-9e9a-c8682d7b3d17-attachment.txt", "type": "text/plain"}], "start": 1743504726304, "stop": 1743504726304, "uuid": "71d6ce80-2e5c-42b1-adb3-bbec247a2533", "historyId": "af86c6d3f761fa1af41f76cfa4e21366", "testCaseId": "af86c6d3f761fa1af41f76cfa4e21366", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_delete_test_plan_api_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}