{"name": "test_get_test_plans_error", "status": "passed", "description": "Test get test plans exception.", "attachments": [{"name": "log", "source": "62b8d873-205b-494e-a2bc-7439f027712e-attachment.txt", "type": "text/plain"}], "start": 1743505054835, "stop": 1743505054835, "uuid": "ab03382d-5133-4952-9af4-4c71259114b8", "historyId": "a32464ce7f4aee6358ef19307204284b", "testCaseId": "a32464ce7f4aee6358ef19307204284b", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperNegative#test_get_test_plans_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperNegative"}, {"name": "host", "value": "fv-az1673-369"}, {"name": "thread", "value": "2350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}