{"name": "test_delete_test_suite_logs_error", "status": "passed", "description": "Test logger called when API deletion fails", "start": 1743499569985, "stop": 1743499569986, "uuid": "d3ba6ff5-9cb9-4080-8d4a-3403420df612", "historyId": "64808f58e18ca9f88c6f7a5b54743d27", "testCaseId": "64808f58e18ca9f88c6f7a5b54743d27", "fullName": "src.tests.ado.test_plan.test_unit_ado_test_plan.TestPlanApiWrapperExceptions#test_delete_test_suite_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_test_plan"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.test_plan"}, {"name": "suite", "value": "test_unit_ado_test_plan"}, {"name": "subSuite", "value": "TestPlanApiWrapperExceptions"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.test_plan.test_unit_ado_test_plan"}]}