{"name": "test_get_comments_api_error", "status": "passed", "description": "Test getting comments when the API call fails.", "attachments": [{"name": "log", "source": "eeed50dd-66c4-4e53-8923-67acefd95bac-attachment.txt", "type": "text/plain"}], "start": 1743499571380, "stop": 1743499571381, "uuid": "20c41d2a-7cbe-4d53-8839-f757b709e701", "historyId": "6c9d3a1e10c6e139aa7af086e2b9ed6e", "testCaseId": "6c9d3a1e10c6e139aa7af086e2b9ed6e", "fullName": "src.tests.ado.work_item.test_unit_ado_wrapper.TestAdoWorkItemWrapper#test_get_comments_api_error", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "ado"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.work_item"}, {"name": "suite", "value": "test_unit_ado_wrapper"}, {"name": "subSuite", "value": "TestAdoWorkItemWrapper"}, {"name": "host", "value": "fv-az1120-17"}, {"name": "thread", "value": "2592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.work_item.test_unit_ado_wrapper"}]}