{"name": "test_get_wiki_page_by_id_logs_error", "status": "passed", "description": "Test logger called when extraction fails due to an API error.", "start": 1743504727832, "stop": 1743504727832, "uuid": "3670757d-cb8e-4086-b7b0-f952a235b59c", "historyId": "08e2faf70a12b41c278a6a61f024267b", "testCaseId": "08e2faf70a12b41c278a6a61f024267b", "fullName": "src.tests.ado.wiki.test_unit_ado_wiki.TestWikiApiWrapperExceptions#test_get_wiki_page_by_id_logs_error", "labels": [{"name": "tag", "value": "exception_handling"}, {"name": "tag", "value": "ado_wiki"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "src.tests.ado.wiki"}, {"name": "suite", "value": "test_unit_ado_wiki"}, {"name": "subSuite", "value": "TestWikiApiWrapperExceptions"}, {"name": "host", "value": "fv-az1927-746"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.ado.wiki.test_unit_ado_wiki"}]}